### ISSUE TITLE
【Build Error】No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

### ISSUE THREAD

**Issue by Liyuu8** [Liyuu8/workplace_clone#1]
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Waiting for Android SDK built for x86 to report its views...
Debug service listening on ws://127.0.0.1:60073/p2fg6c8jKuU=/ws
Syncing files to device Android SDK built for x86...
I/workplace_clon(17542): Background young concurrent copying GC freed 12055(787KB) AllocSpace objects, 10(344KB) LOS objects, 38% free, 2261KB/3665KB, paused 27.436ms total 477.273ms
D/EGL_emulation(17542): eglMakeCurrent: 0xd6a1a720: ver 3 0 (tinfo 0xd6a0f090)
D/eglCodecCommon(17542): setVertexArrayObject: set vao to 0 (0) 1 0
I/OpenGLRenderer(17542): Davey! duration=10664ms; Flags=1, IntendedVsync=94608566193011, Vsync=94608732859671, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=94608743245783, AnimationStart=94608743314783, PerformTraversalsStart=94608743367783, DrawStart=94618716697783, SyncQueued=94618717986783, SyncStart=94618722724783, IssueDrawCommandsStart=94618726235783, SwapBuffers=94618911075783, FrameCompleted=94619235800783, DequeueBufferDuration=78841000, QueueBufferDuration=582000, 
I/Choreographer(17542): Skipped 627 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(17542): eglMakeCurrent: 0xdeb12ba0: ver 3 0 (tinfo 0xd34c1480)
D/eglCodecCommon(17542): setVertexArrayObject: set vao to 0 (0) 1 0

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following FirebaseException was thrown building MyApp(dirty):
[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

The relevant error-causing widget was:
  MyApp file:///Users/liyuu_riyuu/AndroidStudioProjects/workplace_clone/lib/main.dart:25:16

When the exception was thrown, this was the stack:
#0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:118:5)
#1      Firebase.app (package:firebase_core/src/firebase.dart:52:41)
#2      FirebaseFirestore.instance (package:cloud_firestore/src/firestore.dart:43:21)
#3      new DatabaseManager (package:workplace_clone/models/db/database_manager.dart:14:51)
#4      independentModels.<anonymous closure> (package:workplace_clone/di/providers.dart:21:20)
#5      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:641:35)
#6      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:504:33)
#7      Provider.of (package:provider/src/provider.dart:267:29)
#8      new ProxyProvider.<anonymous closure> (package:provider/src/proxy_provider.dart:158:22)
#9      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:665:35)
#10     _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:504:33)
#11     Provider.of (package:provider/src/provider.dart:267:29)
#12     ReadContext.read (package:provider/src/provider.dart:593:21)
#13     viewModels.<anonymous closure> (package:workplace_clone/di/providers.dart:34:31)
#14     _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:641:35)
#15     _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:504:33)
#16     Provider.of (package:provider/src/provider.dart:267:29)
#17     MyApp.build (package:workplace_clone/main.dart:32:37)
#18     StatelessElement.build (package:flutter/src/widgets/framework.dart:4620:28)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#26     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (7 frames)
#36     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
...     Normal element mounting (7 frames)
#43     _NestedHookElement.mount (package:nested/nested.dart:188:11)
#44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#47     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (7 frames)
#57     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
...     Normal element mounting (7 frames)
#64     _NestedHookElement.mount (package:nested/nested.dart:188:11)
#65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#68     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (7 frames)
#78     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
...     Normal element mounting (7 frames)
#85     _NestedHookElement.mount (package:nested/nested.dart:188:11)
...     Normal element mounting (7 frames)
#92     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
#93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#95     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1174:16)
#96     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#97     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1087:17)
#98     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
#99     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1086:13)
#100    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:927:7)
#101    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:908:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following FirebaseException was thrown building MyApp(dirty):
[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

The relevant error-causing widget was: 
  MyApp file:///Users/liyuu_riyuu/AndroidStudioProjects/workplace_clone/lib/main.dart:25:16
When the exception was thrown, this was the stack: 
#0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:118:5)
#1      Firebase.app (package:firebase_core/src/firebase.dart:52:41)
#2      FirebaseFirestore.instance (package:cloud_firestore/src/firestore.dart:43:21)
#3      new DatabaseManager (package:workplace_clone/models/db/database_manager.dart:14:51)
#4      independentModels.<anonymous closure> (package:workplace_clone/di/providers.dart:21:20)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Liyuu8** [comment]
https://stackoverflow.com/questions/63492211/no-firebase-app-default-has-been-created-call-firebase-initializeapp-in

Fourth Example を採用して解決。
